import type { BusinessAlias } from "@/lib/types";

export const businessAliases: BusinessAlias[] = [
  {
    archetype: "beleza",
    aliases: [
      "barbearia",
      "barber",
      "barber shop",
      "salao",
      "salao de beleza",
      "cabeleireiro",
      "manicure",
      "designer de sobrancelha",
      "estetica",
      "clinica estetica",
    ],
  },
  {
    archetype: "saude",
    aliases: [
      "clinica",
      "clinica odontologica",
      "dentista",
      "odontologia",
      "psicologo",
      "fisioterapia",
      "nutricionista",
      "dermatologista",
      "medico",
      "laboratorio",
    ],
  },
  {
    archetype: "alimentacao",
    aliases: [
      "hamburgueria",
      "hamburgueria artesanal",
      "restaurante",
      "pizzaria",
      "lanchonete",
      "cafeteria",
      "padaria",
      "sushi",
      "delivery",
      "doceria",
    ],
  },
  {
    archetype: "varejo",
    aliases: [
      "loja",
      "loja feminina",
      "loja de roupas",
      "moda feminina",
      "boutique",
      "calcados",
      "acessorios",
      "otica",
      "papelaria",
      "presentes",
    ],
  },
  {
    archetype: "automotivo",
    aliases: [
      "mecanica",
      "oficina",
      "auto center",
      "lava rapido",
      "martelinho",
      "funilaria",
      "borracharia",
      "estetica automotiva",
      "concessionaria",
      "auto eletrica",
    ],
  },
  {
    archetype: "fitness",
    aliases: [
      "academia",
      "personal trainer",
      "crossfit",
      "pilates",
      "studio fitness",
      "box",
      "funcional",
      "yoga",
      "musculacao",
    ],
  },
  {
    archetype: "pet",
    aliases: [
      "pet shop",
      "banho e tosa",
      "veterinaria",
      "veterinario",
      "hotel pet",
      "creche pet",
      "adestramento",
      "racao",
    ],
  },
  {
    archetype: "educacao",
    aliases: [
      "escola",
      "curso",
      "aulas",
      "mentoria",
      "idiomas",
      "reforco escolar",
      "faculdade",
      "professor",
    ],
  },
  {
    archetype: "casa_reforma",
    aliases: [
      "arquitetura",
      "engenharia",
      "marcenaria",
      "moveis planejados",
      "construtora",
      "reforma",
      "pintura",
      "decoracao",
      "jardinagem",
    ],
  },
  {
    archetype: "servico_local",
    aliases: [
      "contabilidade",
      "advogado",
      "lavanderia",
      "chaveiro",
      "assistencia tecnica",
      "eletricista",
      "encanador",
      "seguranca",
      "imobiliaria",
      "consultoria",
    ],
  },
];
