import type { BusinessAlias } from "@/lib/types";

export const businessAliases: BusinessAlias[] = [
  {
    archetype: "beleza",
    aliases: [
      "barbearia",
      "barber",
      "barber shop",
      "salão",
      "salão de beleza",
      "cabeleireiro",
      "manicure",
      "designer de sobrancelha",
      "estética",
      "clínica estética",
    ],
  },
  {
    archetype: "saude",
    aliases: [
      "clínica",
      "clínica odontológica",
      "dentista",
      "odontologia",
      "psicólogo",
      "fisioterapia",
      "nutricionista",
      "dermatologista",
      "médico",
      "laboratório",
    ],
  },
  {
    archetype: "alimentacao",
    aliases: [
      "hamburgueria",
      "hamburgueria artesanal",
      "restaurante",
      "pizzaria",
      "lanchonete",
      "cafeteria",
      "padaria",
      "sushi",
      "delivery",
      "doceria",
    ],
  },
  {
    archetype: "varejo",
    aliases: [
      "loja",
      "loja feminina",
      "loja de roupas",
      "moda feminina",
      "boutique",
      "calçados",
      "acessórios",
      "ótica",
      "papelaria",
      "presentes",
    ],
  },
  {
    archetype: "automotivo",
    aliases: [
      "mecânica",
      "oficina",
      "auto center",
      "lava rápido",
      "martelinho",
      "funilaria",
      "borracharia",
      "estética automotiva",
      "concessionária",
      "auto elétrica",
    ],
  },
  {
    archetype: "fitness",
    aliases: [
      "academia",
      "personal trainer",
      "crossfit",
      "pilates",
      "studio fitness",
      "box",
      "funcional",
      "yoga",
      "musculação",
    ],
  },
  {
    archetype: "pet",
    aliases: [
      "pet shop",
      "banho e tosa",
      "veterinária",
      "veterinário",
      "hotel pet",
      "creche pet",
      "adestramento",
      "ração",
    ],
  },
  {
    archetype: "educacao",
    aliases: [
      "escola",
      "curso",
      "aulas",
      "mentoria",
      "idiomas",
      "reforço escolar",
      "faculdade",
      "professor",
    ],
  },
  {
    archetype: "casa_reforma",
    aliases: [
      "arquitetura",
      "engenharia",
      "marcenaria",
      "móveis planejados",
      "construtora",
      "reforma",
      "pintura",
      "decoração",
      "jardinagem",
    ],
  },
  {
    archetype: "servico_local",
    aliases: [
      "contabilidade",
      "advogado",
      "lavanderia",
      "chaveiro",
      "assistência técnica",
      "eletricista",
      "encanador",
      "segurança",
      "imobiliária",
      "consultoria",
    ],
  },
];
