import type { Archetype, ArchetypeData } from "@/lib/types";

export const archetypes: Record<Archetype, ArchetypeData> = {
  beleza: {
    id: "beleza",
    name: "Beleza e autocuidado",
    saleModel: "Agendamento e recorrência",
    visualStrength: "alta",
    trustNeed: "medio",
    urgencyStyle: "agenda",
    toneProfile: ["premium", "aspiracional", "direto"],
    allowedAngles: [
      "transformacao",
      "bastidores",
      "prova_social",
      "autoridade",
      "promocao",
      "venda_direta",
      "novidade",
      "rotina",
      "resultado",
      "objecao",
    ],
    strategyDescription:
      "Negócios de beleza vendem melhor quando o público enxerga transformação, cuidado no detalhe e segurança para agendar.",
    bestApproach: "Transformação visual, prova social e desejo com agenda clara",
  },
  saude: {
    id: "saude",
    name: "Saúde e bem-estar clínico",
    saleModel: "Consulta e avaliação",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["tecnico", "acolhedor", "direto"],
    allowedAngles: [
      "autoridade",
      "educacao",
      "confianca",
      "prova_social",
      "rotina",
      "resultado",
      "objecao",
      "curiosidade",
    ],
    strategyDescription:
      "Na saúde, a decisão depende de confiança, clareza e sensação de cuidado. Conteúdos educativos reduzem insegurança antes do contato.",
    bestApproach: "Autoridade acessível, educação e prova de cuidado",
  },
  alimentacao: {
    id: "alimentacao",
    name: "Alimentação e delivery",
    saleModel: "Pedido imediato e recorrência",
    visualStrength: "alta",
    trustNeed: "baixo",
    urgencyStyle: "desejo",
    toneProfile: ["direto", "urgente", "acolhedor"],
    allowedAngles: [
      "apetite",
      "produto_destaque",
      "bastidores",
      "promocao",
      "venda_direta",
      "novidade",
      "rotina",
      "urgencia",
      "engajamento_local",
    ],
    strategyDescription:
      "Alimentação converte quando ativa desejo rápido, mostra textura e facilita o pedido no momento de fome.",
    bestApproach: "Desejo visual, oferta simples e chamada imediata para pedido",
  },
  varejo: {
    id: "varejo",
    name: "Varejo e loja local",
    saleModel: "Produto e oportunidade",
    visualStrength: "alta",
    trustNeed: "medio",
    urgencyStyle: "sazonal",
    toneProfile: ["direto", "premium", "urgente"],
    allowedAngles: [
      "produto_destaque",
      "promocao",
      "venda_direta",
      "novidade",
      "prova_social",
      "rotina",
      "engajamento_local",
      "objecao",
    ],
    strategyDescription:
      "O varejo precisa transformar variedade em escolha. Bons conteúdos destacam produto, contexto de uso e motivo para comprar agora.",
    bestApproach: "Produto em destaque, recomendação objetiva e prova de procura",
  },
  automotivo: {
    id: "automotivo",
    name: "Automotivo e manutenção",
    saleModel: "Serviço técnico local",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["tecnico", "direto", "acolhedor"],
    allowedAngles: [
      "confianca",
      "educacao",
      "bastidores",
      "autoridade",
      "resultado",
      "rotina",
      "objecao",
      "urgencia",
    ],
    strategyDescription:
      "Serviços automotivos exigem confiança técnica. Conteúdos fortes mostram diagnóstico, prevenção e bastidores do cuidado.",
    bestApproach: "Diagnóstico claro, prevenção e bastidores técnicos",
  },
  fitness: {
    id: "fitness",
    name: "Fitness e performance",
    saleModel: "Plano recorrente e acompanhamento",
    visualStrength: "alta",
    trustNeed: "medio",
    urgencyStyle: "desejo",
    toneProfile: ["aspiracional", "direto", "urgente"],
    allowedAngles: [
      "transformacao",
      "resultado",
      "rotina",
      "prova_social",
      "educacao",
      "promocao",
      "venda_direta",
      "objecao",
    ],
    strategyDescription:
      "Fitness vende evolução possível. A melhor comunicação combina resultado, rotina real e convite para começar com orientação.",
    bestApproach: "Evolução visível, consistência e quebra de objeções",
  },
  pet: {
    id: "pet",
    name: "Pet e cuidado animal",
    saleModel: "Serviço recorrente e produto complementar",
    visualStrength: "alta",
    trustNeed: "alto",
    urgencyStyle: "agenda",
    toneProfile: ["acolhedor", "direto", "premium"],
    allowedAngles: [
      "bastidores",
      "confianca",
      "transformacao",
      "rotina",
      "produto_destaque",
      "educacao",
      "prova_social",
      "engajamento_local",
    ],
    strategyDescription:
      "No universo pet, o tutor precisa sentir cuidado real. Bastidores, carinho e segurança tornam o contato mais natural.",
    bestApproach: "Cuidado visível, confiança e rotina acolhedora",
  },
  servico_local: {
    id: "servico_local",
    name: "Serviço local",
    saleModel: "Orçamento e atendimento sob demanda",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["direto", "tecnico", "acolhedor"],
    allowedAngles: [
      "autoridade",
      "confianca",
      "bastidores",
      "prova_social",
      "educacao",
      "resultado",
      "venda_direta",
      "objecao",
      "engajamento_local",
    ],
    strategyDescription:
      "Serviços locais ganham valor quando deixam claro o processo, a rapidez de resposta e a segurança de contratar alguém confiável.",
    bestApproach: "Confiança, clareza de processo e chamada para orçamento",
  },
  educacao: {
    id: "educacao",
    name: "Educação e cursos",
    saleModel: "Matrícula, mentoria ou aula",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "desejo",
    toneProfile: ["tecnico", "acolhedor", "aspiracional"],
    allowedAngles: [
      "autoridade",
      "educacao",
      "prova_social",
      "rotina",
      "resultado",
      "promocao",
      "objecao",
      "curiosidade",
    ],
    strategyDescription:
      "Educação precisa provar método e possibilidade de avanço. Conteúdos bons mostram clareza, progresso e segurança para começar.",
    bestApproach: "Método, evolução e prova de aprendizado",
  },
  casa_reforma: {
    id: "casa_reforma",
    name: "Casa, obra e reforma",
    saleModel: "Orçamento e projeto",
    visualStrength: "alta",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["tecnico", "direto", "premium"],
    allowedAngles: [
      "transformacao",
      "resultado",
      "bastidores",
      "confianca",
      "autoridade",
      "prova_social",
      "objecao",
      "venda_direta",
    ],
    strategyDescription:
      "Casa e reforma dependem de confiança e visual forte. Transformações e bastidores reduzem medo de erro e aumentam valor percebido.",
    bestApproach: "Antes e depois, processo transparente e acabamento",
  },
};
