import type { Archetype, ArchetypeData } from "@/lib/types";

export const archetypes: Record<Archetype, ArchetypeData> = {
  beleza: {
    id: "beleza",
    name: "Beleza e autocuidado",
    saleModel: "agendamento e recorrencia",
    visualStrength: "alta",
    trustNeed: "medio",
    urgencyStyle: "agenda",
    toneProfile: ["premium", "aspiracional", "direto"],
    allowedAngles: [
      "transformacao",
      "bastidores",
      "prova_social",
      "autoridade",
      "promocao",
      "novidade",
      "rotina",
      "resultado",
    ],
  },
  saude: {
    id: "saude",
    name: "Saude e bem-estar clinico",
    saleModel: "consulta e avaliacao",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["tecnico", "acolhedor", "direto"],
    allowedAngles: ["autoridade", "educacao", "confianca", "prova_social", "rotina", "resultado"],
  },
  alimentacao: {
    id: "alimentacao",
    name: "Alimentacao e delivery",
    saleModel: "pedido imediato e recorrencia",
    visualStrength: "alta",
    trustNeed: "baixo",
    urgencyStyle: "desejo",
    toneProfile: ["direto", "urgente", "acolhedor"],
    allowedAngles: ["apetite", "produto_destaque", "bastidores", "promocao", "novidade", "rotina"],
  },
  varejo: {
    id: "varejo",
    name: "Varejo e loja local",
    saleModel: "produto e oportunidade",
    visualStrength: "alta",
    trustNeed: "medio",
    urgencyStyle: "sazonal",
    toneProfile: ["direto", "premium", "urgente"],
    allowedAngles: ["produto_destaque", "promocao", "novidade", "prova_social", "rotina"],
  },
  automotivo: {
    id: "automotivo",
    name: "Automotivo e manutencao",
    saleModel: "servico tecnico local",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["tecnico", "direto", "acolhedor"],
    allowedAngles: ["confianca", "educacao", "bastidores", "autoridade", "resultado", "rotina"],
  },
  fitness: {
    id: "fitness",
    name: "Fitness e performance",
    saleModel: "plano recorrente e acompanhamento",
    visualStrength: "alta",
    trustNeed: "medio",
    urgencyStyle: "desejo",
    toneProfile: ["aspiracional", "direto", "urgente"],
    allowedAngles: ["transformacao", "resultado", "rotina", "prova_social", "educacao", "promocao"],
  },
  pet: {
    id: "pet",
    name: "Pet e cuidado animal",
    saleModel: "servico recorrente e produto complementar",
    visualStrength: "alta",
    trustNeed: "alto",
    urgencyStyle: "agenda",
    toneProfile: ["acolhedor", "direto", "premium"],
    allowedAngles: ["bastidores", "confianca", "transformacao", "rotina", "produto_destaque", "educacao"],
  },
  servico_local: {
    id: "servico_local",
    name: "Servico local",
    saleModel: "orcamento e atendimento sob demanda",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["direto", "tecnico", "acolhedor"],
    allowedAngles: ["autoridade", "confianca", "bastidores", "prova_social", "educacao", "resultado"],
  },
  educacao: {
    id: "educacao",
    name: "Educacao e cursos",
    saleModel: "matricula, mentoria ou aula",
    visualStrength: "media",
    trustNeed: "alto",
    urgencyStyle: "desejo",
    toneProfile: ["tecnico", "acolhedor", "aspiracional"],
    allowedAngles: ["autoridade", "educacao", "prova_social", "rotina", "resultado", "promocao"],
  },
  casa_reforma: {
    id: "casa_reforma",
    name: "Casa, obra e reforma",
    saleModel: "orcamento e projeto",
    visualStrength: "alta",
    trustNeed: "alto",
    urgencyStyle: "dor",
    toneProfile: ["tecnico", "direto", "premium"],
    allowedAngles: ["transformacao", "resultado", "bastidores", "confianca", "autoridade", "prova_social"],
  },
};
